"""add template_namespace to tenant_whatsapp

Revision ID: 19d0f9403cd3
Revises: 3ae98eccef74
Create Date: 2026-09-01 14:16:06.551098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d0f9403cd3'
down_revision: Union[str, None] = '3ae98eccef74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_whatsapp', sa.Column('template_namespace', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_whatsapp', 'template_namespace')
    # ### end Alembic commands ###
