"""add config_json to tenants

Revision ID: cbb2bc067d7a
Revises: f1a2b3c4d5e6
Create Date: 2026-09-17 12:19:41.269158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb2bc067d7a'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('tenants', sa.Column('config_json', sa.String(), nullable=False, server_default=''))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'config_json')
    # ### end Alembic commands ###
